apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  labels:
    name: payment-configmap
    app: payment
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  PAYMENT_SERVICE_HOST: "0.0.0.0"
  PAYMENT_SERVICE_PORT: "50057"
  PAYMENT_HEALTH_CHECK_PORT: "8087"
  USER_SERVICE_HOST: "user-svc"
  USER_SERVICE_PORT: "50052"
  NOTIFICATION_SERVICE_HOST: "notification-svc"
  NOTIFICATION_SERVICE_PORT: "50056"
  NOTIFICATION_QUEUE_NAME: "notification-queue"
  PP_MERCHANT_BASE_URL: "https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay"
  PP_MERCHANT_STATUS_URL: "https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/status"
  # PP_REDIRECT_URL: "http://localhost:5001/payment/status"
  PP_REDIRECT_URL: "https://circle.planetunknown.xyz/payment/status"
  PP_SUCCESS_URL: "https://circle-client-sigma.vercel.app/payment-success"
  PP_FAILURE_URL: "https://circle-client-sigma.vercel.app/payment-failed"

  # prod phone pay status and pay urls
  # prod_URL: "https://api.phonepe.com/apis/hermes/pg/v1/pay"
  # prod_URL: "https://api.phonepe.com/apis/hermes/pg/v1/status"
