services:
  api-gateway:
    build: ./apiGateway
    container_name: api-gateway
    ports: 
      - 5001:5001
    volumes:
      - ./apiGateway:/app
      - ./apiGateway/node_modules:/app/node_modules
    depends_on:
      - auth-service
      - user-service
    environment:
      - LOGGER_DB=${GT_LOGGER_DB}
      - AUTH_SERVICE_HOST=${GT_AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - USER_SERVICE_HOST=${GT_USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - 50051:50051
      - 8081:8081
    volumes:
      - ./auth:/app
      - node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl" , "-f" , "http://localhost:8081/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - HEALTH_CHECK_PORT=${AUTH_HEALTH_CHECK_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - USER_DB_URI=${USER_DB_URI}
      - LOGGER_DB=${AUTH_LOGGER_DB}

  user-service:
    build: ./userService
    container_name: user-service
    ports: 
      - 50052:50052
      - 8082:8082
    volumes:
      - ./userService:/app
      - ./userService/node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8082/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - HEALTH_CHECK_PORT=${USER_HEALTH_CHECK_PORT}
      - USER_DB_URI=${USER_DB_URI}
      - LOGGER_DB=${USER_LOGGER_DB}

  post-service:
    build: ./postService
    container_name: post-service
    ports: 
      - 50053:50053
      - 8083:8083
    volumes:
      - ./postService:/app
      - ./postService/node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8083/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - POST_SERVICE_PORT=${POST_SERVICE_PORT}
      - POST_SERVICE_HOST=${POST_SERVICE_HOST}
      - POST_HEALTH_CHECK_PORT=${POST_HEALTH_CHECK_PORT}
      - POST_DB_URI=${POST_DB_URI}



volumes:
  node_modules: 