apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    name: auth-svc
    app: auth
  namespace: circle
spec:
  type: ClusterIP
  selector: 
    name: auth-pod
    app: auth
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8081
      targetPort: 8081