apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 12arunkb@gmail.com #  Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
        - circle.planetunknown.xyz
      http01:
        ingress:
          name: web-ingress
    - selector:
        dnsZones:
        - circle-notification.planetunknown.xyz
      http01:
        ingress:
          name: notification-ingress

   