apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  labels:
    name: notification-configmap
    app: notification
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  NOTIFICATION_SERVICE_HOST: "0.0.0.0"
  NOTIFICATION_SERVICE_PORT: "50056"
  NOTIFICATION_HEALTH_CHECK_PORT: "8086"
  NOTIFICATION_HEALTH_CHECK_PORT_2: "5086"
  NOTIFICATION_QUEUE_NAME: "notification-queue"
  GT_QUEUE_HOST: "rabbitmq-svc"
  GT_QUEUE_PORT: "5672"
  FEED_SERVICE_HOST: "feed-svc"
  FEED_SERVICE_PORT: "50054"
  GT_USER_SERVICE_HOST: "user-svc"
  USER_SERVICE_PORT: "50052"
  POST_CACHE_HOST: "cache-svc"
  POST_CACHE_PORT: "6379"
