apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: notification-backendconfig
  namespace: circle
spec:
  healthCheck:
    requestPath: /health
    port: 5086
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
