apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
  labels:
    name: notification-deploy
    app: notification
  namespace: circle
spec:
  replicas: 1
  selector:
    matchLabels:
      name: notification-pod
      app: notification
  template:
    metadata:
      name: notification-pod
      labels:
        name: notification-pod
        app: notification
    spec:
      initContainers:
      - name: wait-for-cache
        image: busybox
        command: 
        - sh
        - -c 
        - | 
          echo "Waiting for cache service to be available..."
          until nslookup cache-svc.circle.svc.cluster.local; do
            echo "cache-svc not available yet, sleeping..."
            sleep 2
          done;
          echo "cache-svc is up!"
      - name: wait-for-rabbitmq
        image: busybox
        command: 
        - sh
        - -c 
        - | 
          echo "Waiting for rabbitmq service to be available..."
          until nslookup rabbitmq-svc.circle.svc.cluster.local; do
            echo "rabbitmq-svc not available yet, sleeping..."
            sleep 2
          done;
          echo "rabbitmq-svc is up!"
      - name: wait-for-user
        image: busybox
        command: 
        - sh
        - -c 
        - | 
          echo "Waiting for user service to be available..."
          until nslookup user-svc.circle.svc.cluster.local; do
            echo "user-svc not available yet, sleeping..."
            sleep 2
          done;
          echo "user-svc is up!"
      - name: wait-for-feed
        image: busybox
        command: 
        - sh
        - -c 
        - | 
          echo "Waiting for feed service to be available..."
          until nslookup feed-svc.circle.svc.cluster.local; do
            echo "feed-svc not available yet, sleeping..."
            sleep 2
          done;
          echo "feed-svc is up!"

      containers:
      - name: notification-service
        image: arun0kb/circle-notification-service:1.0.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: notification-secret
        - configMapRef:
            name: notification-configmap
        readinessProbe:
          httpGet:
            path: /health
            port: 5086
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5086
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3