apiVersion: v1
kind: Service
metadata:
  name: cache-svc
  labels:
    name: cache-svc
    app: cache
  namespace: circle
spec:
  type: ClusterIP
  selector: 
    name: cache-pod
    app: cache
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379