apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deploy
  labels:
    name: chat-deploy
    app: chat
  namespace: circle
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chat-pod
      app: chat
  template:
    metadata:
      name: chat-pod
      labels:
        name: chat-pod
        app: chat
    spec:
      initContainers:
      - name: wait-for-user
        image: busybox
        command: 
        - sh
        - -c 
        - | 
          echo "Waiting for user service to be available..."
          until nslookup user-svc.circle.svc.cluster.local; do
            echo "user-svc not available yet, sleeping..."
            sleep 2
          done;
          echo "user-svc is up!"

      containers:
      - name: chat-service
        image: arun0kb/circle-chat-service:1.0.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: chat-secret
        - configMapRef:
            name: chat-configmap
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3