apiVersion: v1
kind: ConfigMap
metadata:
  name: post-configmap
  labels:
    name: post-configmap
    app: post
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  API_GATEWAY_PORT: "5001"
  API_GATEWAY_HOST: "api-gateway-svc"
  POST_SERVICE_PORT: "50053"
  POST_SERVICE_HOST: "0.0.0.0"
  POST_HEALTH_CHECK_PORT: "8083"
  GT_QUEUE_HOST: "rabbitmq-svc"
  GT_QUEUE_PORT: "5672"
  POST_CACHE_HOST: "cache-svc"
  POST_CACHE_PORT: "6379"
  USER_SERVICE_HOST: "user-svc"
  USER_SERVICE_PORT: "50052"
  NOTIFICATION_QUEUE_NAME: "notification-queue"

  NOTIFICATION_SERVICE_HOST: ""
  NOTIFICATION_SERVICE_PORT: ""
  PP_SUCCESS_URL: ""
  PP_FAILURE_URL: ""
