apiVersion: v1
kind: Service
metadata:
  name: post-svc
  labels:
    name: post-svc
    app: post
  namespace: circle
spec:
  type: ClusterIP
  selector: 
    name: post-pod
    app: post
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
    - name: http
      port: 8083
      targetPort: 8083