apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-configmap
  labels:
    name: feed-configmap
    app: feed
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  FEED_SERVICE_HOST: "0.0.0.0"
  FEED_SERVICE_PORT: "50054"
  FEED_HEALTH_CHECK_PORT: "8084"
  POST_CACHE_HOST: "cache-svc"
  POST_CACHE_PORT: "6379"
  GT_USER_SERVICE_HOST: "user-svc"
  USER_SERVICE_PORT: "50052"
