apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    name: notification-svc
    app: notification
  namespace: circle
spec:
  type: NodePort
  selector: 
    name: notification-pod
    app: notification
  ports:
    - name: grpc
      port: 50056
      targetPort: 50056
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30002