apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    name: rabbitmq-deploy
    app: rabbitmq
  namespace: circle
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-pod
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        name: rabbitmq-pod
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-service
        image: rabbitmq:3-management
        imagePullPolicy: Always
        envFrom:
        - secretRef:
           name: rabbitmq-secret
        readinessProbe:
          httpGet:
            path: /
            port: 15672
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 15672
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3