apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    name: rabbitmq-svc
    app: rabbitmq
  namespace: circle
spec:
  type: ClusterIP
  selector: 
    name: rabbitmq-pod
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672