apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  labels:
    name: user-configmap
    app: user
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  USER_SERVICE_HOST: "0.0.0.0"
  USER_SERVICE_PORT: "50052"
  USER_HEALTH_CHECK_PORT: "8082"

  GT_QUEUE_HOST: "rabbitmq"
  GT_QUEUE_PORT: "5672"
  NOTIFICATION_SERVICE_HOST: "notification-svc"
  NOTIFICATION_SERVICE_PORT: "50056"
