apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backendconfig
  namespace: circle
spec:
  timeoutSec: 300
  healthCheck:
    requestPath: /health
    port: 5080
    checkIntervalSec: 60
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
