apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
  labels:
    name: api-gateway-configmap
    app: api-gateway
  namespace: circle
data:
  CORN_EXPRESSION: "0 0 * * *"
  DOCKER_IMAGE_TAG: "1.0.0"
  DOCKER_USERNAME: "arun0kb"

  API_GATEWAY_PORT: "5001"
  API_GATEWAY_HOST: "localhost"

  AUTH_SERVICE_HOST: "auth-svc"
  AUTH_SERVICE_PORT: "50051"
  USER_SERVICE_HOST: "user-svc"
  USER_SERVICE_PORT: "50052"
  POST_SERVICE_HOST: "post-svc"
  POST_SERVICE_PORT: "50053"
  FEED_SERVICE_HOST: "feed-svc"
  FEED_SERVICE_PORT: "50054"
  CHAT_SERVICE_HOST: "chat-svc"
  CHAT_SERVICE_PORT: "50055"
  NOTIFICATION_SERVICE_HOST: "notification-svc"
  NOTIFICATION_SERVICE_PORT: "50056"
  NOTIFICATION_QUEUE_NAME: "notification-queue"
  POST_CACHE_HOST: "cache-svc"
  POST_CACHE_PORT: "6379"
  GT_QUEUE_HOST: "rabbitmq-svc"
  GT_QUEUE_PORT: "5672"  
  PAYMENT_SERVICE_HOST: "payment-svc"
  PAYMENT_SERVICE_PORT: "50057"
  PP_SUCCESS_URL: "http://localhost:5173/payment-success"
  PP_FAILURE_URL: "http://localhost:5173/payment-failed"