apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  labels:
    name: api-gateway-svc
    app: api-gateway
  namespace: circle
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "api-gateway-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    name: api-gateway-pod
    app: api-gateway
  ports:
    - name: http
      port: 5001
      targetPort: 5001
      # nodePort: 30001